controller_manager:
  ros__parameters:
    update_rate: 50
    state_broadcaster:
      type: pi3hat_state_broadcaster/Pi3Hat_State_Broadcaster 
 

state_broadcaster:
  ros__parameters:
    joints:
      - "LF_HFE"
      - "LF_KFE"
      - "LH_HFE"
      - "LH_KFE"
      - "RF_HFE"
      - "RF_KFE"
      - "RH_HFE"
      - "RH_KFE"
    # second_encoders:
    #   - "LF_HFE"
    #   - "LF_KFE"
    #   - "LH_HFE"
    #   - "LH_KFE"
    #   - "RF_HFE"
    #   - "RF_KFE"
    #   - "RH_HFE"
    #   - "RH_KFE"
    
    performance_index: true



