controller_manager:
  ros__parameters:
    update_rate: 1000
    state_broadcaster:
      type: pi3hat_state_broadcaster/Pi3Hat_State_Broadcaster
    joint_controller:
      type: pi3hat_joint_group_controller/Pi3Hat_Joint_Group_Controller
state_broadcaster:
  ros__parameters:
    joints:
      - joint
      # - jnt_b9_1Hz_trq4_c2
      # - jnt_b9_1Hz_trq4_c3
      # - joinjoint1t3
      # - joint4
    performance_index: true
joint_controller:
  ros__parameters:
    joints:
      - joint
      # - jnt_b9_1Hz_trq4_c2
      # - jnt_b9_1Hz_trq4_c3
      # - joinjoint1t3
      # - joint4
    


