controller_manager:
  ros__parameters:
    update_rate: 100 # hz tutto
    state_broadcaster:
      type: pi3hat_state_broadcaster/Pi3Hat_State_Broadcaster # stampa roba su topic 
    joint_controller:
      type: pi3hat_joint_group_controller/Pi3Hat_Joint_Group_Controller # prende messaggi da topic 
    OM_controller:
      type: pi3hat_vel_controller/Pi3Hat_Vel_Controller
    IMU_Broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2 
      # - jnt_b9_1Hz_trq4_c2
      # - jnt_b9_1Hz_trq4_c3
      # - joinjoint1t3
      # - joint4
    second_encoders:
      - joint1
      - joint2
    performance_index: true
OM_controller:
  ros__parameters:
    homing_duration: 5.0
    input_frequency: 100
IMU_Broadcaster:
  ros__parameters:
    sensor_name: "IMU"
    frame_id: "IMU_NAV"
    


