controller_manager:
  ros__parameters:
    update_rate: 450
    state_broadcaster:
      type: pi3hat_state_broadcaster/Pi3Hat_State_Broadcaster
state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    performance_index: true


