controller_manager:
  ros__parameters:
    update_rate: 800

    pd_joint_state:
      type: rbt_pd_cnt/Real_PD_Cnt
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pd_joint_state:
  ros__parameters:
    joint: 
      - joint1
      - joint2
    init_pos:
      - 0.0
      - 0.0
    
